from qwen_agent.tools.base import BaseTool, register_tool
import json, json5
import asyncio
from playwright.async_api import Playwright, async_playwright, expect

@register_tool('navigate_url')
class MyYoutubeTool(BaseTool):
    description ='navigate to the given url'
    parameters = [
        {
            'name': 'url',
            'type': 'string',
            'description': 'The URL to interact/navigate with',
            'required': True
        },
    ]

    async def call(self, params: str, **kwargs) -> str:
        # `params` are the arguments generated by the LLM agent.
        url = json5.loads(params)['url']
        
        async def run(playwright: Playwright) -> None:
            browser = await playwright.chromium.launch(headless=False)
            context = await browser.new_context()
            page = await context.new_page()
            await page.goto(url)
            
            # await context.close()
            # await browser.close()
        
        async def main() -> None:
            async with async_playwright() as playwright:
                await run(playwright)
        
        asyncio.run(main())
        return json.dumps({'message': 'navigate interaction successful'})