from duckduckgo_search import DDGS, AsyncDDGS
import json, json5
from qwen_agent.tools.base import BaseTool, register_tool

@register_tool('my_video_searcher')
class MyVideoSearcher(BaseTool):
    description ='search for videos on the internet'
    parameters = [
        {
            'name': 'keywords',
            'type': 'string',
            'description': 'The keywords to search for',
            'required': True
        },
        {
            'name': 'safesearch',
            'type': 'string',
            'description': 'The safesearch setting',
            'required': False
        },
        {
            'name': 'max_results',
            'type': 'int',
            'description': 'The maximum number of results',
            'required': False
        },
    ]

    def call(self, params: str, **kwargs) -> str:
        # `params` are the arguments generated by the LLM agent.
        keywords = json5.loads(params)['keywords']
        safesearch = json5.loads(params).get('safesearch', 'off')
        max_results = json5.loads(params).get('max_results', 100)

        results = DDGS().videos(
            keywords=keywords,
            safesearch=safesearch,
            max_results=max_results,
        )

        return json.dumps(results)

    async def call_async(self, params: str, **kwargs) -> str:
        # `params` are the arguments generated by the LLM agent.
        keywords = json5.loads(params)['keywords']
        safesearch = json5.loads(params).get('safesearch', 'off')
        max_results = json5.loads(params).get('max_results', 100)

        results = await AsyncDDGS().avideos(
            keywords=keywords,            safesearch=safesearch,
            max_results=max_results,
        )

        return json.dumps(results)